version: "2.4"  # optional since v1.27.0
services:
  postgres:
    image: postgres
    container_name: 'postgres'
    restart: always
    environment:
      POSTGRES_DB: "${mysql_db_name}"
      POSTGRES_USER: "${mysql_user_name}"
      POSTGRES_PASSWORD: "${mysql_password}"
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  mongo:
    image: mongo:3.6.0
    container_name : 'mongodb'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "${mongo_db_name}"
      MONGO_INITDB_ROOT_USERNAME: "${mongo_root_name}"
      MONGO_INITDB_ROOT_PASSWORD: "${mongo_root_password}"
#      DB_NAME:"${mongo_db}"
#      DB_USER:"${mongo_user}"
#      DB_PASSWORD:"${mongo_password}"
    ports:
      - '27017-27019:27017-27019'
    expose:
      - '27017-27019'
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/mongo:/data/db      



  
